apiVersion: v1
data:
  config.yaml: |
    static_resources:
      listeners:
      - name: http
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 80
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              access_log:
              - name: envoy.file_access_log
                config:
                  path: "/dev/stdout"
              codec_type: auto
              stat_prefix: ingress_http
              use_remote_address: true
              http_protocol_options:
                accept_http_10: true
              route_config:
                name: local_route
                virtual_hosts:
                - name: "dummy"
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: SOME-APP
              http_filters:
              - name: envoy.router
                config: {}

      clusters:
      - name: SOME-APP
        http_protocol_options: {}
        connect_timeout: 3s
        type: strict_dns
        dns_lookup_family: v4_only
        lb_policy: least_request
        hosts:
        - socket_address:
              address: SOME-SERVICE.NAMESPACE.svc.cluster.local
              port_value: 5000

    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001

kind: ConfigMap
metadata:
  name: envoy-config
